Settlements
intergiro/cli pull request #48
Opened 2021-11-15 14:41 UTC by robinnedergard

2021-11-15 16:06 UTC, marcushanses approved these changes

2021-11-16 12:36 UTC, Magnus93 requested changes

2021-11-16 12:36 UTC, Magnus93 commented on Test/settlement.ts
> +	yesterday: string
Set isoly.Date type

2021-11-18 12:06 UTC, Magnus93 approved these changes

2021-12-16 13:31 UTC, closed without merging